### ISSUE TITLE
`pip install aestream` results in compilation error for OpenCV

### ISSUE THREAD

**Issue by emijan-kth** [aestream/aestream#66]
OS: Ubuntu 22.04.2

Steps to reproduce:

1. Install libcaer:

```
sudo add-apt-repository ppa:inivation-ppa/inivation
sudo apt update
sudo apt install libcaer-dev
```
(The above step will automatically install opencv: apt package `libopencv-core4.5d` with dependencies)

2. Install aestream:

`pip install aestream`

Now, the install will fail with the following error message:

```
     FAILED: src/input/CMakeFiles/aestream_input.dir/inivation.cpp.o
      /usr/bin/c++ -DWITH_CAER -Daestream_input_EXPORTS -I/tmp/pip-install-znyihc6g/aestream_544ff65d37eb499e9cebf51ec87b1619/include -I/opt/homebrew/opt/lz4/include -I/tmp/pip-install-znyihc6g/aestream_544ff65d37eb499e9cebf51ec87b1619/src -I/tmp/pip-install-znyihc6g/aestream_544ff65d37eb499e9cebf51ec87b1619/_skbuild/linux-x86_64-3.10/cmake-build/src/file/fb_headers -I/tmp/pip-install-znyihc6g/aestream_544ff65d37eb499e9cebf51ec87b1619/_skbuild/linux-x86_64-3.10/cmake-build/_deps/flatbuffers-src/include -O3 -DNDEBUG -std=gnu++20 -fPIC -fcoroutines -MD -MT src/input/CMakeFiles/aestream_input.dir/inivation.cpp.o -MF src/input/CMakeFiles/aestream_input.dir/inivation.cpp.o.d -o src/input/CMakeFiles/aestream_input.dir/inivation.cpp.o -c /tmp/pip-install-znyihc6g/aestream_544ff65d37eb499e9cebf51ec87b1619/src/input/inivation.cpp
      In file included from /usr/include/libcaercpp/devices/davis.hpp:4,
                       from /tmp/pip-install-znyihc6g/aestream_544ff65d37eb499e9cebf51ec87b1619/src/input/./inivation.hpp:11,
                       from /tmp/pip-install-znyihc6g/aestream_544ff65d37eb499e9cebf51ec87b1619/src/input/inivation.cpp:1:
      /usr/include/libcaercpp/events/frame.hpp:20:17: fatal error: opencv2/core.hpp: No such file or directory
         20 | #       include <opencv2/core.hpp>
            |                 ^~~~~~~~~~~~~~~~~~
```

Full output: [aestream_install_log.txt](https://github.com/norse/aestream/files/11109863/aestream_install_log.txt)

**Comment by Jegp** [comment]
Thanks for reporting this!

As far as I understand, it should be perfectly possibly to install libcaer without reference to OpenCV (cf. https://gitlab.com/inivation/dv/libcaer/ on `-DENABLE_OPENCV`). Do you need OpenCV? If not, we could consider disabling it for now.

One thing I haven't fully figured out yet is how to add camera drivers to the pip install. I could imagine there are roughly two approaches

1. Pull them down with [CPM](https://github.com/cpm-cmake/CPM.cmake/) during build. That would mean camera drivers are included in *every* installation (rather than having sub-dependencies like `aestream[torch]`). But if we precompile the wheels, this would perhaps be ok?
2. Create independent PyPi projects that prepare drivers that `aestream` can depend on. For instance `aestream-drivers`. That would mean creating a separate repository/project, but would make it nicer to install (e.g. `pip pinstall aestream[inivation]` and `pip install aestream[prophesee]`)

Any opinions? Preferences? Alternatives? :)

**Comment by Jegp** [comment]
Ping @emijan-kth :)

**Comment by Jegp** [comment]
Closing for now. You are welcome to reopen if this is still a problem
